--- 
- name: nginx. Install packages
  yum:
    name: "{{ yum_http_packages }}"
    state: present
- name: nginx. Enable and start service
  service:
    name: nginx
    state: started
    enabled: yes
